### ISSUE TITLE
OwnCloud provisioning problems on wheezy [transient?]

### ISSUE THREAD

**Issue by jmcgnh** [jmcgnh/sovereign#11]
# Encountered while resuming the provsioning of debian(7)

TASK: [owncloud | Ensure repository key for ownCloud is in place for Debian 7] **\* 
changed: [debian]

TASK: [owncloud | Add ownCloud OpenSuSE repository for Debian 7] *************\* 
failed: [debian] => {"failed": true, "parsed": false}
BECOME-SUCCESS-gnhjblqkncyyxwhdipovekqxmauqgihp
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1450765498.52-41218821707997/apt_repository", line 2749, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1450765498.52-41218821707997/apt_repository", line 436, in main
    cache.update()
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 418, in update
    raise FetchFailedException(e)
apt.cache.FetchFailedException: W:Failed to fetch http://http.debian.net/debian/dists/wheezy-backports/Release.gpg  Error reading from server. Remote end closed connection [IP: 5.153.231.35 80]
, E:Some index files failed to download. They have been ignored, or old ones used instead.
OpenSSH_6.9p1 Ubuntu-2, OpenSSL 1.0.2d 9 Jul 2015
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 127.0.0.1 closed.

FATAL: all hosts have already failed -- aborting

**Comment by jmcgnh** [comment]
Again, seems like a transient error. Retrying the provisioning gets past this point.

**Comment by jmcgnh** [comment]
Closing as transient. Probably cause by temporary network glitch.
