### ISSUE TITLE
nosetests on Jessie branch vagrant provision

### ISSUE THREAD

**Issue by jmcgnh** [jmcgnh/sovereign#16]
> nosetests
> E..F.....F..E/home/jmcg/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
>   InsecureRequestWarning)
> # .EEEEEE..
> ## ERROR: ZNC is accepting encrypted logins
> 
> Traceback (most recent call last):
>   File "/opt/software/sovereign/jmcg-sovereign-jessie/tests.py", line 147, in test_irc_auth
>     ssl_sock.connect((TEST_SERVER, 6697))
>   File "/usr/lib/python2.7/ssl.py", line 844, in connect
>     self._real_connect(addr, False)
>   File "/usr/lib/python2.7/ssl.py", line 835, in _real_connect
>     self.do_handshake()
>   File "/usr/lib/python2.7/ssl.py", line 808, in do_handshake
>     self._sslobj.do_handshake()
> SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
# 
## ERROR: Blog is redirecting to https

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign-jessie/tests.py", line 34, in test_blog_http
    self.assertEquals(r.history[0].status_code, 301)
IndexError: list index out of range
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): sovereign.local
requests.packages.urllib3.connectionpool: DEBUG: "GET / HTTP/1.1" 403 233
--------------------- >> end captured logging << ---------------------
# 
## ERROR: Email autoconfiguration XML file is accessible over both HTTP and HTTPS

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign-jessie/tests.py", line 45, in test_mail_autoconfig_http_and_https
    r = requests.get(proto + '://autoconfig.' + TEST_SERVER + '/mail/config-v1.1.xml')
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): autoconfig.sovereign.local
requests.packages.urllib3.connectionpool: DEBUG: "GET /mail/config-v1.1.xml HTTP/1.1" 200 1196
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): autoconfig.sovereign.local
--------------------- >> end captured logging << ---------------------
# 
## ERROR: ownCloud is redirecting to https and displaying login page

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign-jessie/tests.py", line 93, in test_owncloud_http
    r = requests.get('http://cloud.' + TEST_SERVER)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 597, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 195, in resolve_redirects
    *_adapter_kwargs
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): cloud.sovereign.local
requests.packages.urllib3.connectionpool: DEBUG: "GET / HTTP/1.1" 301 246
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): cloud.sovereign.local
--------------------- >> end captured logging << ---------------------
# 
## ERROR: selfoss is redirecting to https and displaying login page

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign-jessie/tests.py", line 108, in test_selfoss_http
    r = requests.get('http://news.' + TEST_SERVER)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 597, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 195, in resolve_redirects
    *_adapter_kwargs
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): news.sovereign.local
requests.packages.urllib3.connectionpool: DEBUG: "GET / HTTP/1.1" 301 245
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): news.sovereign.local
--------------------- >> end captured logging << ---------------------
# 
## ERROR: Webmail is redirecting to https and displaying login page

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign-jessie/tests.py", line 54, in test_webmail_http
    r = requests.get('http://mail.' + TEST_SERVER)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 597, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 195, in resolve_redirects
    *_adapter_kwargs
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): mail.sovereign.local
requests.packages.urllib3.connectionpool: DEBUG: "GET / HTTP/1.1" 301 245
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): mail.sovereign.local
--------------------- >> end captured logging << ---------------------
# 
## ERROR: test_zpush_http_unauthorized (tests.WebTests)

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign-jessie/tests.py", line 68, in test_zpush_http_unauthorized
    r = requests.get('http://mail.' + TEST_SERVER + '/Microsoft-Server-ActiveSync')
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 597, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 195, in resolve_redirects
    *_adapter_kwargs
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): mail.sovereign.local
requests.packages.urllib3.connectionpool: DEBUG: "GET /Microsoft-Server-ActiveSync HTTP/1.1" 301 262
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): mail.sovereign.local
--------------------- >> end captured logging << ---------------------
# 
## ERROR: test_zpush_https (tests.WebTests)

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign-jessie/tests.py", line 83, in test_zpush_https
    'Cmd': 'Ping',
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): mail.sovereign.local
--------------------- >> end captured logging << ---------------------
# 
## FAIL: Connects with POP3S and asserts the existance of an email, then deletes it

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign-jessie/tests.py", line 361, in test_pop3s
    self.assertPOP3Received(subject)
  File "/opt/software/sovereign/jmcg-sovereign-jessie/tests.py", line 215, in assertPOP3Received
    self.assertTrue("Subject: " + subject in text)
AssertionError: False is not true
# 
## FAIL: Email sent from an MUA has DKIM and TLS headers

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign-jessie/tests.py", line 307, in test_smtps_headers
    data[0][1]
AssertionError: 'DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=sovereign.local;' not found in 'Return-Path: sovereign@sovereign.local\r\nDelivered-To: sovereign@sovereign.local\r\nReceived: from mail.sovereign.local\r\n\tby mail.sovereign.local (Dovecot) with LMTP id CgRxLC9af1ZsFwAAMLZLsA\r\n\tfor sovereign@sovereign.local; Sun, 27 Dec 2015 03:25:51 +0000\r\nReceived: from [127.0.1.1](unknown [172.16.100.1])\r\n\t(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))\r\n\t(No client certificate requested)\r\n\tby mail.sovereign.local (Postfix) with ESMTPSA id 4599D36268\r\n\tfor root@sovereign.local; Sun, 27 Dec 2015 03:25:51 +0000 (UTC)\r\nContent-Type: text/plain; charset="us-ascii"\r\nMIME-Version: 1.0\r\nContent-Transfer-Encoding: 7bit\r\nSubject: 3cb524d8\r\nFrom: sovereign@sovereign.local\r\nTo: root@sovereign.local\r\n\r\nTesting\r\n'

---

Ran 22 tests in 28.294s

FAILED (errors=8, failures=2)

**Comment by jmcgnh** [comment]
New issue #23 takes over from this one.
