### ISSUE TITLE
issues with tests.py

### ISSUE THREAD

**Issue by jmcgnh** [jmcgnh/sovereign#4]
Debian7 branch provisioning now proceeds to conclusion without additional errors.

Starting to try tests.py.

First thing that happened was:

> python tests.py
> Traceback (most recent call last):
>   File "tests.py", line 5, in <module>
>     import requests
> ImportError: No module named requests

**Comment by jmcgnh** [comment]
Ran

sudo apt-get install python-pip

pip install requests

**Comment by jmcgnh** [comment]
Can now run

python tests.py

but nothing seems to happen. Simulating some of the tests I see some behavior that should have been flagged as failures, so something's not right about the tests.

**Comment by jmcgnh** [comment]
Seem to have lost a post here....

Found I could run the tests with

python -m unittest discover

and got some useful feedback finally. Several of the errors appeared to have the same root cause: the wildcard cert built into the ansible environment had expired. Created my own wildcard cert and moved it into place and the errors started to be more specific.

**Comment by jmcgnh** [comment]
The first error had to do with certificate validity, so which led to updating "pip" and installing the certifi module:

easy_install -U pip

pip install certifi

Now we'll see if the tests give more specific errors about the distinct components.

**Comment by jmcgnh** [comment]
OK, both provisionings have run through to completion. Errors seen now seem to be the same on both branches.

Debian7 branch:

> python -m unittest discover
> 
> # E....F...F..EEEEEEEEE..
> 
> ERROR: test_irc_auth (tests.IRCTests)
> 
> ## ZNC is accepting encrypted logins
> 
> Traceback (most recent call last):
>   File "/opt/software/sovereign/jmcg-sovereign/tests.py", line 164, in test_irc_auth
>     ssl_sock.connect((TEST_SERVER, 6697))
>   File "/usr/lib/python2.7/ssl.py", line 844, in connect
>     self._real_connect(addr, False)
>   File "/usr/lib/python2.7/ssl.py", line 831, in _real_connect
>     socket.connect(self, addr)
>   File "/usr/lib/python2.7/socket.py", line 228, in meth
>     return getattr(self._sock,name)(*args)
> error: [Errno 111] Connection refused

# 

ERROR: test_blog_http (tests.WebTests)

## Blog is redirecting to https

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign/tests.py", line 33, in test_blog_http
    r = requests.get('http://' + TEST_SERVER, verify=False)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='sovereign.local', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe47422dad0>: Failed to establish a new connection: [Errno 111] Connection refused',))

# 

ERROR: test_cgit_http (tests.WebTests)

## CGit web interface is displaying home page

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign/tests.py", line 129, in test_cgit_http
    r = requests.get('http://git.' + TEST_SERVER, verify=False)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='git.sovereign.local', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe47419b3d0>: Failed to establish a new connection: [Errno 111] Connection refused',))

# 

ERROR: test_mail_autoconfig_http_and_https (tests.WebTests)

## Email autoconfiguration XML file is accessible over both HTTP and HTTPS

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign/tests.py", line 47, in test_mail_autoconfig_http_and_https
    r = requests.get(proto + '://autoconfig.' + TEST_SERVER + '/mail/config-v1.1.xml')
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='autoconfig.sovereign.local', port=80): Max retries exceeded with url: /mail/config-v1.1.xml (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe47419b490>: Failed to establish a new connection: [Errno 111] Connection refused',))

# 

ERROR: test_newebe_http (tests.WebTests)

## Newebe is displaying home page

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign/tests.py", line 144, in test_newebe_http
    r = requests.get('http://newebe.' + TEST_SERVER, verify=False)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='newebe.sovereign.local', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe47419b590>: Failed to establish a new connection: [Errno 111] Connection refused',))

# 

ERROR: test_owncloud_http (tests.WebTests)

## ownCloud is redirecting to https and displaying login page

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign/tests.py", line 95, in test_owncloud_http
    r = requests.get('http://cloud.' + TEST_SERVER)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='cloud.sovereign.local', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe47419b510>: Failed to establish a new connection: [Errno 111] Connection refused',))

# 

ERROR: test_selfoss_http (tests.WebTests)

## selfoss is redirecting to https and displaying login page

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign/tests.py", line 110, in test_selfoss_http
    r = requests.get('http://news.' + TEST_SERVER)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='news.sovereign.local', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe47419b690>: Failed to establish a new connection: [Errno 111] Connection refused',))

# 

ERROR: test_webmail_http (tests.WebTests)

## Webmail is redirecting to https and displaying login page

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign/tests.py", line 56, in test_webmail_http
    r = requests.get('http://mail.' + TEST_SERVER)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='mail.sovereign.local', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe47419b750>: Failed to establish a new connection: [Errno 111] Connection refused',))

# 

## ERROR: test_zpush_http_unauthorized (tests.WebTests)

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign/tests.py", line 70, in test_zpush_http_unauthorized
    r = requests.get('http://mail.' + TEST_SERVER + '/Microsoft-Server-ActiveSync')
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='mail.sovereign.local', port=80): Max retries exceeded with url: /Microsoft-Server-ActiveSync (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe47419b890>: Failed to establish a new connection: [Errno 111] Connection refused',))

# 

## ERROR: test_zpush_https (tests.WebTests)

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign/tests.py", line 85, in test_zpush_https
    'Cmd': 'Ping',
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='mail.sovereign.local', port=443): Max retries exceeded with url: /Microsoft-Server-ActiveSync?Cmd=Ping&DeviceType=testbot&DeviceId=1234 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe47419b990>: Failed to establish a new connection: [Errno 111] Connection refused',))

# 

FAIL: test_smtp_headers (tests.MailTests)

## Email sent from an MTA via SMTP+TLS has X-DSPAM and TLS headers

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign/tests.py", line 360, in test_smtp_headers
    data[0][1]
AssertionError: 'X-DSPAM-Result: ' not found in 'Return-Path: someone@example.com\r\nDelivered-To: sovereign@sovereign.local\r\nReceived: from mail.sovereign.local\r\n\tby mail.sovereign.local (Dovecot) with LMTP id FlNeECGQclawHgAAMLZLsA\r\n\tfor sovereign@sovereign.local; Thu, 17 Dec 2015 10:36:20 +0000\r\nReceived: from [127.0.1.1](unknown [172.16.100.1])\r\n\t(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))\r\n\t(No client certificate requested)\r\n\tby mail.sovereign.local (Postfix) with ESMTPS id 2B8322788C0\r\n\tfor sovereign@sovereign.local; Thu, 17 Dec 2015 10:36:20 +0000 (UTC)\r\nContent-Type: text/plain; charset="us-ascii"\r\nMIME-Version: 1.0\r\nContent-Transfer-Encoding: 7bit\r\nSubject: d15d3b66\r\nFrom: someone@example.com\r\nTo: sovereign@sovereign.local\r\n\r\nTesting\r\n'

# 

FAIL: test_smtps_headers (tests.MailTests)

## Email sent from an MUA has DKIM and TLS headers

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign/tests.py", line 323, in test_smtps_headers
    data[0][1]
AssertionError: 'DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=sovereign.local;' not found in 'Return-Path: sovereign@sovereign.local\r\nDelivered-To: sovereign@sovereign.local\r\nReceived: from mail.sovereign.local\r\n\tby mail.sovereign.local (Dovecot) with LMTP id JlNeECGQclawHgAAMLZLsA\r\n\tfor sovereign@sovereign.local; Thu, 17 Dec 2015 10:36:25 +0000\r\nReceived: from [127.0.1.1](unknown [172.16.100.1])\r\n\t(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))\r\n\t(No client certificate requested)\r\n\tby mail.sovereign.local (Postfix) with ESMTPSA id 031BE2788C0\r\n\tfor root@sovereign.local; Thu, 17 Dec 2015 10:36:25 +0000 (UTC)\r\nContent-Type: text/plain; charset="us-ascii"\r\nMIME-Version: 1.0\r\nContent-Transfer-Encoding: 7bit\r\nSubject: dbc32ac6\r\nFrom: sovereign@sovereign.local\r\nTo: root@sovereign.local\r\n\r\nTesting\r\n'

---

Ran 23 tests in 19.186s

# FAILED (failures=2, errors=10)

while on jessie branch I am seeing:

> python -m unittest discover
> 
> # E........F..EEEEEEEE..
> 
> ERROR: test_irc_auth (tests.IRCTests)
> 
> ## ZNC is accepting encrypted logins
> 
> Traceback (most recent call last):
>   File "/opt/software/sovereign/jmcg-sovereign-jessie/tests.py", line 147, in test_irc_auth
>     ssl_sock.connect((TEST_SERVER, 6697))
>   File "/usr/lib/python2.7/ssl.py", line 844, in connect
>     self._real_connect(addr, False)
>   File "/usr/lib/python2.7/ssl.py", line 831, in _real_connect
>     socket.connect(self, addr)
>   File "/usr/lib/python2.7/socket.py", line 228, in meth
>     return getattr(self._sock,name)(*args)
> timeout: timed out

# 

ERROR: test_blog_http (tests.WebTests)

## Blog is redirecting to https

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign-jessie/tests.py", line 31, in test_blog_http
    r = requests.get('http://' + TEST_SERVER, verify=False)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='sovereign.local', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe4ef91b950>: Failed to establish a new connection: [Errno 111] Connection refused',))

# 

ERROR: test_cgit_http (tests.WebTests)

## CGit web interface is displaying home page

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign-jessie/tests.py", line 127, in test_cgit_http
    r = requests.get('http://git.' + TEST_SERVER, verify=False)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='git.sovereign.local', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe4ef88c250>: Failed to establish a new connection: [Errno 111] Connection refused',))

# 

ERROR: test_mail_autoconfig_http_and_https (tests.WebTests)

## Email autoconfiguration XML file is accessible over both HTTP and HTTPS

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign-jessie/tests.py", line 45, in test_mail_autoconfig_http_and_https
    r = requests.get(proto + '://autoconfig.' + TEST_SERVER + '/mail/config-v1.1.xml')
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='autoconfig.sovereign.local', port=80): Max retries exceeded with url: /mail/config-v1.1.xml (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe4ef88c310>: Failed to establish a new connection: [Errno 111] Connection refused',))

# 

ERROR: test_owncloud_http (tests.WebTests)

## ownCloud is redirecting to https and displaying login page

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign-jessie/tests.py", line 93, in test_owncloud_http
    r = requests.get('http://cloud.' + TEST_SERVER)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='cloud.sovereign.local', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe4ef88c410>: Failed to establish a new connection: [Errno 111] Connection refused',))

# 

ERROR: test_selfoss_http (tests.WebTests)

## selfoss is redirecting to https and displaying login page

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign-jessie/tests.py", line 108, in test_selfoss_http
    r = requests.get('http://news.' + TEST_SERVER)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='news.sovereign.local', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe4ef88c450>: Failed to establish a new connection: [Errno 111] Connection refused',))

# 

ERROR: test_webmail_http (tests.WebTests)

## Webmail is redirecting to https and displaying login page

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign-jessie/tests.py", line 54, in test_webmail_http
    r = requests.get('http://mail.' + TEST_SERVER)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='mail.sovereign.local', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe4ef88c510>: Failed to establish a new connection: [Errno 111] Connection refused',))

# 

## ERROR: test_zpush_http_unauthorized (tests.WebTests)

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign-jessie/tests.py", line 68, in test_zpush_http_unauthorized
    r = requests.get('http://mail.' + TEST_SERVER + '/Microsoft-Server-ActiveSync')
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='mail.sovereign.local', port=80): Max retries exceeded with url: /Microsoft-Server-ActiveSync (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe4ef88c650>: Failed to establish a new connection: [Errno 111] Connection refused',))

# 

## ERROR: test_zpush_https (tests.WebTests)

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign-jessie/tests.py", line 83, in test_zpush_https
    'Cmd': 'Ping',
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, *_kwargs)
  File "/home/jmcg/.local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='mail.sovereign.local', port=443): Max retries exceeded with url: /Microsoft-Server-ActiveSync?Cmd=Ping&DeviceType=testbot&DeviceId=1234 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe4ef88c750>: Failed to establish a new connection: [Errno 111] Connection refused',))

# 

FAIL: test_smtps_headers (tests.MailTests)

## Email sent from an MUA has DKIM and TLS headers

Traceback (most recent call last):
  File "/opt/software/sovereign/jmcg-sovereign-jessie/tests.py", line 306, in test_smtps_headers
    data[0][1]
AssertionError: 'DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=sovereign.local;' not found in 'Return-Path: sovereign@sovereign.local\r\nDelivered-To: sovereign@sovereign.local\r\nReceived: from mail.sovereign.local\r\n\tby mail.sovereign.local (Dovecot) with LMTP id WuVIJI2PclZzHgAAMLZLsA\r\n\tfor sovereign@sovereign.local; Thu, 17 Dec 2015 10:33:57 +0000\r\nReceived: from [127.0.1.1](unknown [172.16.100.1])\r\n\t(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))\r\n\t(No client certificate requested)\r\n\tby mail.sovereign.local (Postfix) with ESMTPSA id 88E642788C0\r\n\tfor root@sovereign.local; Thu, 17 Dec 2015 10:33:57 +0000 (UTC)\r\nContent-Type: text/plain; charset="us-ascii"\r\nMIME-Version: 1.0\r\nContent-Transfer-Encoding: 7bit\r\nSubject: 4b0ebdc6\r\nFrom: sovereign@sovereign.local\r\nTo: root@sovereign.local\r\n\r\nTesting\r\n'

---

Ran 22 tests in 27.261s

FAILED (failures=1, errors=9)

**Comment by jmcgnh** [comment]
I'm going to call this resolved. Figuring out

python -m unittest discover

and, reading the "Development Environment" page in the Wiki, to see that I had to install python module 'nose', so that

nosetests

works, resolves this particular issue with the test suite.
